package problems;

import utils.Problem;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class Problem2 implements Problem {

	@Override
	public String solve() {
		int first = 1;
		int second = 2;
		int solution = 2;

		while (true) {
			int third = first + second;

			if(third > 4_000_000) {
				return String.valueOf(solution);
			}

			if(third % 2 == 0) {
				solution += third;
			}

			first = second;
			second = third;
		}
	}
}
